name: Deploy Portfolio to GitHub Pages (Jekyll)

on:
  # Runs on pushes targeting the main branch
  push:
    branches: [ "main" ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# Sets permissions of the GITHUB_TOKEN to allow deployment to GitHub Pages
permissions:
  contents: read
  pages: write
  id-token: write

# Allow only one concurrent deployment
concurrency:
  group: "pages"
  cancel-in-progress: false

jobs:
  # Build job
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout main branch
        uses: actions/checkout@v4
        with:
          ref: main
        
      - name: Setup Node.js 18
        uses: actions/setup-node@v4
        with:
          node-version: '18'
          cache: 'npm'
          
      - name: Install dependencies
        run: npm ci
        
      - name: Build React portfolio for main branch
        run: npm run build
        env:
          NODE_ENV: production
          VITE_BASE_URL: /hellominhaj/
          
      - name: Prepare deployment files
        run: |
          # Create .nojekyll to disable Jekyll processing
          touch ./dist/public/.nojekyll
          # Ensure all assets are properly copied
          ls -la ./dist/public/
          
      - name: Setup GitHub Pages
        uses: actions/configure-pages@v4
        
      - name: Upload artifact to Pages
        uses: actions/upload-pages-artifact@v3
        with:
          path: './dist/public'

  # Deployment job
  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Deploy to GitHub Pages from main
        id: deployment
        uses: actions/deploy-pages@v4